### ISSUE TITLE
Fullfill the open-source checklist

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/inaka.github.io#27]
## General Items
- [x] It has a github repo
- [x] It has a proper LICENSE file
- [x] It's has a clear and useful README.md
- [ ] It's documented
- [x] It's hooked to the [open-source hipchat room](https://www.hipchat.com/gpBpW3SsT)
- [x] It has a link to the [open-source hipchat room](https://www.hipchat.com/gpBpW3SsT) in its README
- [x] It has a link to [inaka.github.io](http://inaka.github.io) in its README and/or landing page

## Exhibition
- [x] There is a blog post about it
- [x] It's shared on social networks
- [x] It's shared on reddit
- [x] It's shared on hacker news with a title like Show HN: description
- [x] It has a landing page built in github pages

## For Erlang Projects
- [x] It's checked with [Elvis](http://github.com/inaka/elvis)
